services:
  rancher:
    image: rancher/rancher:v2.11.3
    container_name: rancher-server
    restart: unless-stopped
    environment:
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./rancher-data:/var/lib/rancher
    privileged: true